"""BAOBAOBOT.md assembly — composes the root BAOBAOBOT.md from shared files.

Reads AGENTS.md and AGENTSOUL.md from shared_dir, then writes a single
assembled BAOBAOBOT.md in the workspace root. Memory (memory/EXPERIENCE.md,
daily memories, summaries) is NOT embedded — Claude Code reads those on demand
via skills (memory-list, memory-search).

A thin CLAUDE.md is also written so Claude Code discovers the instructions.

Key class: ClaudeMdAssembler.
"""

import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# Section order in the assembled BAOBAOBOT.md
# (filename, section_title, source)  — source is "shared" or "workspace"
_SECTION_ORDER = [
    ("AGENTS.md", "Work Instructions (AGENTS)", "shared"),
    ("AGENTSOUL.md", "Agent Soul (AGENTSOUL)", "shared"),
]

_HEADER = """\
# BaoBao Assistant

> This file is auto-generated by BaoBaoClaude. Do not edit manually.
> Last updated: {timestamp}
"""


_CLAUDE_MD_CONTENT = """\
# BaoBao Assistant

Read BAOBAOBOT.md for detailed instructions, personality, and memory context.
"""


class ClaudeMdAssembler:
    """Reads shared persona files, assembles BAOBAOBOT.md."""

    def __init__(self, shared_dir: Path, workspace_dir: Path) -> None:
        self.shared_dir = shared_dir
        self.workspace_dir = workspace_dir
        self.output_path = workspace_dir / "BAOBAOBOT.md"
        self.claude_md_path = workspace_dir / "CLAUDE.md"
        self._source_mtimes: dict[str, float] = {}

    def _read_file(self, path: Path) -> str:
        """Read a file, returning empty string if it doesn't exist."""
        try:
            return path.read_text(encoding="utf-8").strip()
        except OSError:
            return ""

    def _resolve_source_dir(self, source: str) -> Path:
        """Return shared_dir or workspace_dir based on source tag."""
        return self.shared_dir if source == "shared" else self.workspace_dir

    def assemble(self) -> str:
        """Build the full BAOBAOBOT.md content from source files."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        parts: list[str] = [_HEADER.format(timestamp=timestamp)]

        for filename, section_title, source in _SECTION_ORDER:
            source_dir = self._resolve_source_dir(source)
            filepath = source_dir / filename
            content = self._read_file(filepath)
            if content:
                parts.append(f"---\n\n## {section_title}")
                parts.append(content)

        result = "\n\n".join(parts) + "\n"
        # Replace template variables (safety net for old AGENTS.md with {{BIN_DIR}})
        result = result.replace("{{BIN_DIR}}", str(self.shared_dir / "bin"))
        result = result.replace("{{USERS_DIR}}", str(self.shared_dir / "users"))
        result = result.replace("{{WORKSPACE_DIR}}", str(self.workspace_dir))
        return result

    def write(self) -> None:
        """Assemble and write BAOBAOBOT.md + thin CLAUDE.md to the workspace root."""
        content = self.assemble()
        self.output_path.write_text(content, encoding="utf-8")
        logger.info("Assembled BAOBAOBOT.md at %s", self.output_path)

        # Write thin CLAUDE.md that points to BAOBAOBOT.md
        self.claude_md_path.write_text(_CLAUDE_MD_CONTENT, encoding="utf-8")

        # Update mtime cache
        self._update_mtimes()

    def _update_mtimes(self) -> None:
        """Cache modification times of source files."""
        self._source_mtimes = {}
        for filename, _, source in _SECTION_ORDER:
            source_dir = self._resolve_source_dir(source)
            filepath = source_dir / filename
            if filepath.exists():
                self._source_mtimes[f"{source}:{filename}"] = filepath.stat().st_mtime

    def needs_rebuild(self) -> bool:
        """Check if any source file has been modified since last assembly."""
        if not self.output_path.exists():
            return True

        if not self._source_mtimes:
            # No cached mtimes — need rebuild
            return True

        for filename, _, source in _SECTION_ORDER:
            source_dir = self._resolve_source_dir(source)
            filepath = source_dir / filename
            if filepath.exists():
                current_mtime = filepath.stat().st_mtime
                cached = self._source_mtimes.get(f"{source}:{filename}", 0)
                if current_mtime > cached:
                    return True

        return False


def rebuild_all_workspaces(shared_dir: Path, workspace_dirs: list[Path]) -> int:
    """Rebuild BAOBAOBOT.md for all workspaces where sources have changed.

    Returns the number of workspaces rebuilt.
    """
    rebuilt = 0
    for ws in workspace_dirs:
        assembler = ClaudeMdAssembler(shared_dir, ws)
        if assembler.needs_rebuild():
            assembler.write()
            rebuilt += 1
    return rebuilt
